print("Enter rows")
s=input()
print(s)
mylist = s.split(" ")
#print(mylist)
word = max(mylist, key=len)
maxIx=mylist.index(word)
#print(word)
#print(len(word))
print("Найдовшим словом є : %r , з довжиною : %i" %(mylist[maxIx],len(word)))